- MANIFEST
- script/zonemaster-info
I've found this occasionally useful, so I thought I might as well add it on the assumption that someone else may too.
> Add script to print info about a zone.

- lib/Zonemaster/CLI.pm
- script/zonemaster-cli
> Allow lookup of nameservers for undelegated tests.

- LICENSE
- README.md
- docs/installation.md
> modified all instances of .SE to IIS

- Makefile.PL
- lib/Zonemaster/CLI.pm
Fixes packaging issue with version numbering
See dotse/zonemaster#461 for more details
> - Fixes dotse/zonemaster-cli#33

- Makefile.PL
- lib/Zonemaster/CLI.pm
- script/zonemaster-info
@matsduf @mattias-p Need a review for name space changes
> - Fixes dotse/zonemaster-cli#43

- docs/Installation.md
This PR will add the same commits to the develop branch as #75 added to the master branch. This PR is to make sure that the develop branch contains this change.
> Updated the install instructions for debian and centos

- Changes
- lib/Zonemaster/CLI.pm
* Added change log to Changes.
* Updated version number in Engine.pm to the same as the latest in Changes.
> Updates as prepartion for release

- lib/Zonemaster/CLI.pm
- share/da.po
- share/en.po
- share/fr.po
- share/sv.po
Solves #77. It also includes collateral improvements regarding L10N.
> Diagnostics

- lib/Zonemaster/CLI.pm
> Make --level and --stop_level case-insensitive

- lib/Zonemaster/CLI.pm
> Clarify documentation of --progress option

- Changes
- Makefile.PL
- README.md
- docs/Installation.md
- lib/Zonemaster/CLI.pm
- share/da.po
- share/en.po
- share/fr.po
- share/sv.po
Merge current develop into profiles feature branch. No conflicts.
> Merge develop into profiles branch

- .travis.yml
Test against current Zonemaster::Engine develop branch instead of the latest version of Zonemaster::Engine according to CPAN.
> Test against current Engine develop branch 

- .travis.yml
This is what Engine and Backend are already doing.
> Test against Zonemaster::LDNS develop branch

- docs/Installation.md
Added a note on the FreeBSD package system and the need to activate and update it. Also see zonemaster/zonemaster-engine#544.
> Update installation instructions on FreeBSD

- Changes
- lib/Zonemaster/CLI.pm
* Updated Changes
* Updated CLI.pm
> Preparation for release v2.0.1

- Changes
- lib/Zonemaster/CLI.pm
> Preparation for release v2.0.2

- share/da.po
> Translate into da

- share/da.po
Reverts zonemaster/zonemaster-cli#115
By mistake merged into master. The same changes also merged into develop.
> Revert "Translate into da"

- Changes
- lib/Zonemaster/CLI.pm
* Updated version in Perl module CLI.pm
* Updated with recent changes in Changes
> Preperations for release v2019.2 (CLI)

- share/da.po
The master branch is currently different than the latest release on CPAN. In particular the file `share/da.po` is different.
The inconsistency occurred because we accidentally merged a PR for that file into the master branch instead of the develop branch. To mend the situation we added a revert commit to the master branch to get its head back in sync with the latest release at the time. The changes to `da.po` were also merged into the develop branch in a separate PR where they were meant to go in the first place. 
Later we made a new release and merged the develop branch into the master branch as usual. Git noticed two identical changes to `da.po` on both branches and a revert commit for the change on the master branch. After merging the revert commit stays effective on the master branch. …
> Solves inconsistency in master branch.

- lib/Zonemaster/CLI.pm
- Fixes output issue of --nstimes option when no servers are found
- Fixes zonemaster/zonemaster-cli#148
> --nstimes option issue fix

- docs/Installation.md
> Adding Norwegian locale setting to instructions

- Changes
- Makefile.PL
- README.md
- lib/Zonemaster/CLI.pm
* README.md: Removed outdated information and cleaned up. 
* Changes: Updated with changes since last release.
* CLI.pm: Release version
* Makefile.PL: Updated dependencies
> For release v2020.1 (CLI)

- .travis.yml
- Changes
- Makefile.PL
- docs/Installation.md
- lib/Zonemaster/CLI.pm
- share/fr.po
- share/sv.po
> Merge develop into master (CLI)

- MANIFEST
- share/fi.po
This PO file has been sent by email by translator. It needs some corrections before it can be merged. This resolves #191, part 1.
> Add Finnish PO file (CLI)

- docs/Installation.md
> Adds finnish locale to CLI instructions

- lib/Zonemaster/CLI.pm
This PR remove the --dump_config and --dump_policy options for functionalities that were removed.
Fixes zonemaster/zonemaster-cli#145
--dump_config, --dump-config, --dump_policy and --dump-policy do not work any longer.
Use of these options will return "usage" text.
> Clean up removed --dump_config and --dump_policy

- lib/Zonemaster/CLI.pm
This PR improve output where DNS packets are displayed with DEBUG3 level.
Fixes zonemaster/zonemaster-cli#111
Display has been modified
zonemaster-cli --level DEBUG3 nic.fr
> Improve DEBUG3 output

- Dockerfile
- MANIFEST.SKIP
- Makefile.PL
- README.md
This PR provides dockerization of Zonemaster Engine.
This PR fixes zonemaster/zonemaster-cli#216.
Depends on zonemaster/zonemaster-engine#991.
Shout-outs to @andreasschulze, @andreaso and @blacksponge for prior work that I've built on.
This PR adds a docker file and steps to build it.
Follow the new steps in the README file.
> Add Dockerfile to CLI

- share/nb.po
This PR provides an update to the Norwegian translation of CLI messages. The new translation was provided by @repperille in https://github.com/zonemaster/zonemaster-cli/issues/226#issuecomment-971434982.
Inspect the PO file and verify that translations are provided.
> Updates Norwegian translation (CLI)

- share/fi.po
This PR provides an update to the Finnish translation of CLI messages. The new translation was provided by @samisalmensuo in https://github.com/zonemaster/zonemaster-cli/issues/224#issuecomment-974651215
Inspect the PO file and verify that translations are provided.
> Updates Finnish translation (CLI)

- docs/Installation.md
Provide package installation
Install zonemaster cli on debian 11 using (for the develop branch, the instruction in the doc currently install the master branch)
```sh
curl -Ls https://package.zonemaster.net/setup.sh | sudo nightly=yes bash
apt install zonemaster-cli
```
> add package install

- Changes
- Dockerfile
- LICENSE
- MANIFEST.SKIP
- Makefile.PL
- README.md
- USING.md
- docs/Installation.md
- lib/Zonemaster/CLI.pm
- script/zonemaster-cli
- share/GNUmakefile
- share/fi.po
- share/nb.po
- share/sv.po
- share/update-po
Following https://github.com/zonemaster/zonemaster/blob/develop/docs/internal-documentation/maintenance/ReleaseProcess-release.md#16-merge-develop-branch-into-master
> Merge develop into master

- Changes
- Makefile.PL
- lib/Zonemaster/CLI.pm
Updated files:
* Changes
* Makefile.PL
* lib/Zonemaster/CLI.pm
> Preparation for v2021.2.1 release (CLI)

- docs/Installation.md
Add Spanish locale configuration in Installation document.
n/a
Installation document.
Follow installation instructions.
> Missing Spanish locale in Installation document

- share/nb.po
This PR contains an update to the Norwegian language file
Resolves #265 
...
...
> Updated and added Norwegian language translations.

- Changes
- Makefile.PL
- lib/Zonemaster/CLI.pm
Updates for the release.
The Changes file, the version number in CLI.pm file and the version of Engine CLI require.
> Preparation for v2022.1.1 (CLI)

- docs/Installation.md
PR #284 adds a new explicit dependency. It is already installed indirectly. This PR explicitly lists is in the installation document.
Resolves #289.
Documentation only. Review the document. Follow the instructions to verify that it gets installed.
> Update installation instruction Try::Tiny

- Changes
- Makefile.PL
- lib/Zonemaster/CLI.pm
Updates for release v2022.2.
Updates Changes, Makefile.PL and Engine.pm.
This PR will not pass the CI tests until https://github.com/zonemaster/zonemaster-ldns/pull/163 and https://github.com/zonemaster/zonemaster-engine/pull/1166 have been merged.
Review Changes and inspect Makefile.PL and Engine.pm.
> Updates for release v2022.2 (CLI)

- Changes
- Makefile.PL
- lib/Zonemaster/CLI.pm
Updates for release v2022.2.1.
Updates Changes, Makefile.PL and CLI.pm.
Review Changes, and inspect CLI.pm and Makefile.PL
> Updates for release v2022.2.1 (CLI)

- Changes
- Makefile.PL
- lib/Zonemaster/CLI.pm
Prepares for release v2022.2.2
Updates the following files:
* Changes
* lib/Zonemaster/Engine.pm
* Makefile.PL
Review.
> Preparation release v2022.2.2 (CLI)

- Changes
- Makefile.PL
- lib/Zonemaster/CLI.pm
Updates files `Changes`, `Makefile.PL` and `CLI.pm`.
> Preparation for release v2023.1.1 (CLI)

- Changes
- Makefile.PL
- lib/Zonemaster/CLI.pm
Updates files `Changes`, `Makefile.PL` and `CLI.pm`.
> Preparation for release v2023.1.3 (CLI)

- Changes
- Makefile.PL
- lib/Zonemaster/CLI.pm
See https://github.com/zonemaster/zonemaster/blob/develop/docs/internal/maintenance/ReleaseProcess-release.md#15-merge-develop-branch-into-master
> Merge Releases/v2023.1.3 into Master (CLI)

- Changes
- Makefile.PL
- lib/Zonemaster/CLI.pm
Updates files `Changes`, `Makefile.PL` and `CLI.pm`.
> Preparation for release v2023.1.4 (CLI)

- Changes
- Makefile.PL
- lib/Zonemaster/CLI.pm
- script/zonemaster-cli
See https://github.com/zonemaster/zonemaster/blob/develop/docs/internal/maintenance/ReleaseProcess-release.md#15-merge-develop-branch-into-master
> Merge Releases/v2023.1.4 into Master (CLI)

- Changes
- Makefile.PL
- lib/Zonemaster/CLI.pm
Updates files `Changes`, `CLI.pm` and `Makefile.PL`.
> Preparation for v2023.2 release (CLI)

- .travis.yml
This PR updates the Travis configuration file when it comes to Perl versions to be tested. The versions have been taken from the update in https://github.com/zonemaster/zonemaster/pull/1270
Review.
> Update perl version to be tested by Travis (CLI)

- Changes
- Makefile.PL
- lib/Zonemaster/CLI.pm
Updates files `Changes`, `CLI.pm` and `Makefile.PL`.
> Preparation for release v2024.1 (CLI)

- .travis.yml
This PR makes Travis install the same dependencies for CLI as the installation instruction specifies.
Review and make sure Travis passes.
> Updates dependency list

- t/usage.t
This PR fixes spelling of locale names in unit test.
Fixes #392.
Updates some strings in t/usage.t
Unit tests should pass.
> Fix locale spelling

- share/sv.po
- t/po-files.t
This PR updates the Swedish translation.
Fixed #409.
Updates `sv.po` to correspond to current develop branch.
N/A
> Update Swedish translation
