zonemaster/zonemaster-cli

lib/Zonemaster/CLI.pm
Closes dotse/zonemaster-engine#63.
=> Add switch to print total elapsed test time.

lib/Zonemaster/CLI.pm, script/zonemaster-cli
This added the functionality to stream the results as JSON objects which can be used by other programs to follow the progress in a machine readable way.
```
$ zonemaster-cli --json_translate --json_stream --level DEBUG --no-ipv6 example.com
{"args":{"string":"2015-10-16 11:15:45 +0000","time_t":"1444994145"},"level":"DEBUG","message":"SYSTEM:START_TIME string=2015-10-16 11:15:45 +0000, time_t=1444994145","module":"SYSTEM","tag":"START_TIME","timestamp":6.69956207275391e-05}
{"args":{"module":"all","zone":"example.com"},"level":"DEBUG","message":"SYSTEM:TEST_TARGET module=all, zone=example.com","module":"SYSTEM","tag":"TEST_TARGET","timestamp":0.000236988067626953}
...
{"args":{"mname":"sns.dns.icann.org"},"level":"INFO","message":"SOA 'mname' value (sns.dns.icann.org) refers to a NS which …
```
=> Add streaming JSON functionality.

Makefile.PL
`UNIVERSAL::VERSION()` returns a string of the version and the version may not be all numeric so its better to let the function check for the minimum version.
=> Better way to check ExtUtils::MakeMaker version

MANIFEST, share/da.po
This is the first step to solve issue #61. The actual translation must be added to this PR.
=> Adding support for Danish translation.

Makefile.PL, lib/Zonemaster/CLI.pm
Aims to fix [CPANTS errors](https://cpants.cpanauthors.org/release/ZNMSTR/Zonemaster-CLI-v1.1.2) has_license_in_source_file and has_known_license_in_source_file.
=> Move license from Makefile.PL to main module

lib/Zonemaster/CLI.pm
Merge current develop into profiles feature branch. No conflicts.
=> Merge develop into profiles branch

.travis.yml
After dropping support for Ubuntu 14.04, none of the supported platforms use Perl 5.18.
=> Dropped support for Ubuntu 14.04

share/da.po
=> Translate into da

Makefile.PL, docs/Installation.md
Fixes #117.
Also cleans up a useless explicit dependency on a core module.
=> Centos installation

.travis.yml
zonemaster/zonemaster-ldns#51 adds feature checks for Ed25519, but Travis provides an older version of OpenSSL.
=> Updated Travis config after zonemaster-ldns#51

.travis.yml
Reverts zonemaster/zonemaster-cli#114
This wasn't supposed to go into the master branch.
=> Revert "Fix Travis"

docs/Installation.md
The first commit restructures the instruction to the same format as the installation instruction for Engine.
The second commit add instructions for Ubuntu 18.04 to add the locales needed for Zonemaster CLI.
=> Updated installation instruction to activate locales on ubuntu and debian

.gitignore, Makefile.PL, lib/Zonemaster/CLI.pm, share/Makefile
This PR enables the adoption in CLI of the translation workflow we use in Engine.
This will affect the format of the PO files making for a large initial diff. That initial update is excluded from this PR because the PO files are currently not up to date.
Fixes #132. Fixes #147.
=> Update translation workflow

MANIFEST.SKIP
PR #151 updated the way the MO files are generated. Now two copies are created and the one directly under /share should be skipped. PR #151 missed to include a SKIP statement in MANIFEST.SKIP, which is done here, modeled after the statement in Zonemster-Engine.
=> Skip MO files directly under share

lib/Zonemaster/CLI.pm
The Z::E::Translator::data is neither used by zonemaster-cli nor by Zonemaster::Engine itself so there's no need for zonemaster-cli to load it.
=> Remove useless calls to Z::E::Translator::data

lib/Zonemaster/CLI.pm, script/zonemaster-cli
- Add method name (test case) in Logger.
- Fixes zonemaster/zonemaster-engine#578
DO NOT MERGE NOW, do a test first to check if it is what you are waiting for
=> Related to zonemaster-engine issue 578

share/Makefile
This corrects the same issue as zonemaster/zonemaster-engine/pull/804 but in CLI. "-depth 1" has been added to really mirror what the original code wanted to do.
=> Corrected listing of files

MANIFEST.SKIP
share/Zonemaster-CLI.pot is not included in distribution and should be skipped.
=> Updated MANIFEST.SKIP

lib/Zonemaster/CLI.pm
This resolves #182 by moving the setting of IPv4 and IPv6 enabled/disabled until the profile has been loaded.
=> Resolves issue where selected profile overrides IPv4/6 setting in CLI

lib/Zonemaster/CLI.pm
Add headers to all of the lines in `--raw` mode. To tell where new entries begin I added a marker character right after MODULE:TAG. The first line of an entry is marked with an extra SPACE character. The following lines are marked with a '>' character.
When you have headers on all lines you can filter the logs with better precision using grep.
**Edit:** I removed the reference to #111 as this PR solves a different problem.
=> Add headers to every line of multiline log entries

lib/Zonemaster/CLI.pm
Makes the ipv4 and ipv6 options undefined unless explicitly set on the command line. Changes so that the ip setting is only changed if the option is explicitly set on the command line.
This resolves a bug that appeared after #182 was fixed by #183.
The bug is described in  https://github.com/zonemaster/zonemaster-cli/issues/182#issuecomment-762787971.
=> Updates the ipv4 and ipv6 command line options

Makefile.PL
When I run `perl Makefile.PL` on a fresh repository in preparation for running `make dist`, the PO files are updated with fuzzy translations. Engine does not have this problem. This PR adopts the solution from Engine, making sure that the PO files are not updated when running Makefile.PL.
=> Avoid updating PO files for clean repo

docs/Installation.md
* Replace MooseX::Getopt with perl-MooseX-Getopt
* Remove Locale::MsgFmt (not used)
* Remove Locale::TextDomain (use the same one as Engine)
* Work around compolation errors on CentOS 8
=> Update dependencies installation on CentOS

share/da.po
Missing translations in da.po.
=> Danish translation update

Changes, Makefile.PL, lib/Zonemaster/CLI.pm
Updates:
* CLI.pm with new version (v3.1.0)
* Changes
* Makefile.PL (updated dependency)
~~This PR assumes that #205 will be merged before release.~~ DONE.
~~Travis will complain until https://github.com/zonemaster/zonemaster-engine/pull/924 is merged.~~ No, Travis logs
> Warning: prerequisite Zonemaster::Engine 4.002 not found. We have v4.1.1.
but it does not fail. With Github actions we get a failure.
=> Prepares for release of v2021.1 (CLI)

LICENSE
In the copyright statement a range of years is given. That requires updates, but year is not needed.
Nothing is said about copyright for contributors.
Removes year from copyright and give the correct "translation" of Internetstiftelsen. Adds statement about contributor's copyright.
No need to test.
=> Updates license statements (zonemaster-cli)

lib/Zonemaster/CLI.pm, script/zonemaster-cli
This PR add option names with "-" (hyphen) for options with "_" (underscore) in name. There will be a backward compatibility in the next release but I suggest to remove names with underscores in the future.
Fixes zonemaster/zonemaster-cli#159
"New" options are availables.
zonemaster-cli --list-test
=> Make options more user friendly

lib/Zonemaster/CLI.pm
This PR does no longer display full usage in case of incorrect option
Fixes zonemaster/zonemaster-cli#160
Add 'pass_through' option to MooseX::Getopt::GLD  prevents print of a systematic 'usage'.
use invalid option(s), the output will look like
> zonemaster-cli --jljlkfg --list_tests
Unknown option: --jljlkfg 
Run "zonemaster-cli -h" to get the valid options
=> shorter output when option is incorrect

docs/Installation.md
Update installation instruction
* Replace Centos by Rocky Linux
* Replace yum by dnf
* Merge debian and ubuntu sections
* Install the cli, test a domain
=> update installation doc

README.md, USING.md, docs/Installation.md
This PR adds information for how to run Zonemaster-CLI on Docker.
* Adds information on Docker in the USING document
* Corrects the information in the USING document
* Adds table of contents in the USING document
* Adds information of translation in the USING document.
* Removes peripheral information from the USING document
* Removes detailed Docker build documentation and refers to other document.
* Adds referral to the USING document for Docker use.
* Adds table of contents to the Installation document.
* Adds referral to USING for Docker use in the Installation document.
The following documents are updated:
* README.md
* USING.md
* docs/Installation.md
In this PR only documentation is updated. By following the instructions it could be verified.
Note that this PR adds a link to a …
=> Adds information on CLI on Docker

Makefile.PL, share/GNUmakefile, share/update-po
The tools for PO file generation, incl GNUmakefile, have been updated in Zonemaster-Engine (zonemaster/zonemaster-engine#929). The same solution has also been copied to Zonemaster-Backend (zonemaster/zonemaster-backend#891). 
This PR copies the same solution to Zonemaster-CLI to make it possible to have the same instructions for all three repositories.
* Updates GNUmakefile to match those of Engine and Backend
* Adds tool for PO handling from Engine
* Updates Makefile.PL to match the update of share/GNUmakefile
* Updates  share/GNUmakefile
* Adds share/update-po 
* Updates Makefile.PL
1. Update a PO file with this PR.
2. Update the same PO file with before this PR.
3. Compare and verify that all msgid and msgstr are identical.
4. Generat MO files from identical PO files using the two …
=> Update PO tools

MANIFEST.SKIP
`share/update-po` was added to the repository by #222, but not specified in MANIFEST or MANIFEST.SKIP. The PR adds it to MANIFEST.SKIP since it does not makes sense in the distribution.
MANIFEST.SKIP
Make sure that distribution packages can be correctly created.
=> Update MANIFEST.SKIP with missing file

Changes, Makefile.PL, lib/Zonemaster/CLI.pm
* Bumps version in perl module (compared to last release)
* Updates Changes file
At last relase VERSION was `v3.1.0`. During development this has been increased to `v3.5.0` but for this release it should really be `v3.1.1` which it has been reset to in this PR.
Set this version to require latest version of Engine, which is the version that tests have run against.
Updated files:
* Changes
* lib/Zonemaster/CLI.pm
* Makefile.PL
=> Preparation for release v2021.2 (CLI)

USING.md
If zonemaster-cli is run in a non-IPv6 setting then meaningless error messages are outputted unless IPv6 has been turned off for zonemaster-cli. Docker is usually non-IPv6.
This PR updates the document to clarify this.
This documentation only. Follow the instructions to see the behavior.
=> Clarifies IPv6 limitations

USING.md
The locale setting for Spanish is incorrect, and is corrected with this PR.
Document USING.md is updated.
When using the locale setting from the document, `zonemaster-cli` should translate correctly.
=> Corrects Spanish locale setting

.travis.yml
This repository had the same issue with Travis as Zonemaster-Backend as described in https://github.com/zonemaster/zonemaster-backend/pull/945. The fix in this PR is just a copy of the fix in Zonemaster-Backend.
=> Fix travis-perl error (CLI)

USING.md
When an image has been downloaded Docker will normally never look for updated image if the same tag is used. There is a risk that a user will never get an update of Zonemaster. The document has been updated to suggest that `--pull` is used at least sometimes to pull updates.
Updated files:
* USING.md
Follow the instructions in the document to make sure they are correct.
=> Includes information on --pull for Docker

.travis.yml, lib/Zonemaster/CLI.pm, share/da.po, share/es.po, share/fi.po, share/fr.po, share/nb.po, share/sv.po
Replace libidn with libidn2.
https://github.com/zonemaster/zonemaster-ldns/pull/133
* Update Travis dependency
* Replace references to "libidn" with "libidn2"
Using Zonemaster::LDNS (with libidn2 support), Zonemaster should work the same as before.
=> Use libidn2 instead of libidn

lib/Zonemaster/CLI.pm, share/fr.po
Do not crash when a domain is specified with a final dot.
https://github.com/zonemaster/zonemaster-engine/issues/1055
* Remove final dot from domain if not root
* Remove final dot from NS
* `../zonemaster-cli/script/zonemaster-cli --ns ns2.nic.fr. zonemaster.net. --show-testcase` should run the test without crashing
* `../zonemaster-cli/script/zonemaster-cli --ns ns2.nic.fr.. zonemaster.net. --show-testcase` should show an error
* `../zonemaster-cli/script/zonemaster-cli --ns ns2.nic.fr. zonemaster.net.. --show-testcase` should show an error
=> remove domains final dots

script/zonemaster-cli
zonemaster-cli has support for a configuration file, cli.args, for each user, with the same arguments as on the command line. #252 requests a global configuration file. This PR adds a possibility to have such a file.
The global configuration file is hard coded to be /etc/zonemaster/cli.args (Linux style) or /usr/local/etc/zonemaster/cli.args (FreeBSD style), i.e. the same directory as the Backend configuration is stored in by default.
Arguments on the command line takes precedence over the equivalent argument in ~/.zonemaster/cli.args, which takes precedence over the equivalent argument in a global cli.args. Only one global file is used, /etc/zonemaster/cli.args if that exists, else /usr/local/etc/zonemaster/cli.args.
The way the cli.args is read has been updated to support empty lines …
=> Adds global configuration file

docs/Installation.md
With the last release of Ubuntu, .deb packages can be used to install Zonemaster CLI.
\-
* Prefer pre built packages for ubuntu
* Keep the CPAN installation in a separate subsection
Installation on Ubuntu should work. Use nightly packages to test.
```
host $ docker run --rm -it ubuntu:22.04 
container # apt update && apt install -y curl
container # curl -LOs https://package.zonemaster.net/setup.sh
container # nightly=yes sh setup.sh
container # zonemaster-cli --show-testcase --show-module --level info --no-ipv6 zonemaster.net
...
container # apt info zonemaster-cli
Package: zonemaster-cli
Version: 20220523200630-1+deb11ubuntu1
Priority: optional
Section: perl
...
```
=> use pre-built packages for ubuntu

docs/Installation.md
This PR adds missing installation instructions for CentOS Linux 7 (CentOS). The support for CentOS was removed in the v2021.2 release, but was readded in v2022.1 release. The installation instructions were not added.
This is documentation only.
=>  Adds missing installation instructions for CentOS Linux 7 (CLI)

share/da.po
PO file cannot be compiled into MO file due to a bug.
#277 describes the error, but also the problem how to discovering it early.
Fixes the da.po.
Run the distribution process and make sure "make all" works in the root of the respository.
=> Fixes error in PO file that prevents MO to be created

USING.md
This PR adds a note to USING.md about a warning that is outputted when the Docker commands are run on a Mac computer with M1 chip.
Documentation only. Test that the documentation is correct.
=> Add Mac note on USING.md when it comes to Docker

lib/Zonemaster/CLI.pm
Clean up an unused import. In particular one that is about to be deprecated and eventually removed.
The issue zonemaster/zonemaster-engine#1129 has been created to deprecate Zonemaster::Engine::Net::IP.
An unused import is removed.
Run a test using zonemaster-cli. If it doesn't crash we should be good.
=> Clean up unused import

docs/Installation.md
When it comes to referring to internal anchors, we used a mix of upper and lower cases in our Markdown documents. It appears that Github handles this well, but other Markdown to HTML engines suffer to link to the related identifier on the page since they are looking for a perfect match (case sensitively).
This PR is about downcasing all fragments in our Markdown documents.
n/a
Downcase all fragments that refer to internal anchors in our Markdown documents.
Documentation only. Links with the updated fragments should work properly once rendered.
=> Use lowercase fragments when referring to internal headings

lib/Zonemaster/CLI.pm
It is possible to add several domain names on the command line for `zonemaster-cli` but only the first one is used. The others are ignored. This PR changes the behavior and makes it fail if more than one domain is provided.
Fixes #286.
This change could be considered to be a bug fix or a change of the API. Maybe the behavior was on purpose.
Run `zonemaster-cli` with more than one domain name on the command line. It should fail:
```
$ zonemaster-cli iis.se telia.com
Only one domain can be given for testing. Did you forget to prepend an option with '--<OPTION>'?
```
=> Fail multiple domain names in entry

README.md, lib/Zonemaster/CLI.pm
The statement about license in CLI.pm is not correct. In https://github.com/zonemaster/zonemaster-engine/issues/1149 @emollier pointed out the same issue for Zonemaster-LDNS and Zonemaster.Engine.
This PR updates the statement. It also adds the same statement to the README file.
This is documentation change only.
=> Corrects the license statement in CLI.pm

share/GNUmakefile
New Makefile rule to create an empty PO file using the basename provided in the POLANG variable.
Same changes as in https://github.com/zonemaster/zonemaster-engine/pull/1185 and https://github.com/zonemaster/zonemaster-engine/pull/1191
Addresses https://github.com/zonemaster/zonemaster/issues/1131
* Create a new empty PO file
* Set the "Language" field with the language name
* Update the header fields with default value
* "Project-Id-Version: 1.0.0\n"
* "Language-Team: Zonemaster Team\n"
* "Content-Type: text/plain; charset=UTF-8\n"
* Automatically remove comments
Run `make POLANG=xx new-po` and check that the fields are automatically set with the default values.
=> Provide a rule "new-po" to create an empty PO file

lib/Zonemaster/CLI.pm
Show which versions of Zonemaster-LDNS and NL NetLabs LDNS are being used.
Remove module versions.
Addresses https://github.com/zonemaster/zonemaster-cli/issues/181
CLI.pm and version() method.
Verify that the following command returns 2 new lines `LDNS version` and `libldns version`:
```
$ zonemaster-cli --version
Zonemaster-CLI version v5.0.1                                                                                          
Zonemaster-Engine version v4.6.1     
Zonemaster-LDNS version 3.1.0                    
NL NetLabs LDNS version 1.8.3
```
=> Zonemaster::LDNS and libldns versions

lib/Zonemaster/CLI.pm
The CLI has several options to specify which field to display. Such options are not available when using JSON output `--json` or `--json-stream`. This PR make such options work with JSON output.
https://github.com/zonemaster/zonemaster-cli/issues/247#issuecomment-1436650786
* Make `--[no-]show-...` options work with JSON output
* Display translated message tag when passing `--json` and `--json-translate`
Try several combinations using the `--[no-]show-...` and/or `--[no-]time` options and check that the fields are properly displayed or not. Also check that the combination `--json --json-translate` properly return the translated message.
```
$ zonemaster-cli --no-show-module --show-testcase --test connectivity --level INFO --json --json-translate afnic.fr | jq
[
{
"args": {
"version": …
```
=> Make `--[no-]show-...` options work with JSON output

lib/Zonemaster/CLI.pm
Continue the work to align the Zonemaster-CLI implementation with its own documentation.
Follow-up on #308 
https://github.com/zonemaster/zonemaster-cli/issues/247#issuecomment-1436650786
* Make `--json-stream` entail `--json`
* Deprecate `--[no-]json-translate`, use `--[no-]raw` instead
* Refactor CLI.pm
Test several configurations mixing `--json`, `--raw`, `--json-stream`.
```
zonemaster-cli --json-stream --raw zonemaster.net
zonemaster-cli --json-stream zonemaster.net
zonemaster-cli --json zonemaster.net
zonemaster-cli --json --raw zonemaster.net
zonemaster-cli --json --json-stream --raw zonemaster.net
```
=> Improve implementation for JSON and raw options

MANIFEST, MANIFEST.SKIP
Unit tests for PO files are only relevant for CI tests, not for tests at installation. This PR removes the PO file tests from the distribution package.
Fixes #319
Makes t/po-files.t not being included in the distribution package.
Make sure that Travis passes and installation works.
=> Remove PO tests from distribution package

lib/Zonemaster/CLI.pm
Provide options to define both source IPv4 and source IPv6. This would replace the `--sourceaddr` option.
#315 
Follow-up on https://github.com/zonemaster/zonemaster-engine/pull/1203
* New options "--sourceaddr4" and "--sourceaddr6"
* Deprecate "--sourceaddr".
```
zonemaster-cli --sourceaddr <IP address> bzh # should emit a deprecation message
zonemaster-cli --sourceaddr4 <IPv4 address> berlin
zonemaster-cli --sourceaddr6 <IPv6 address> tokyo
```
=> New options "--sourceaddr4" and "--sourceaddr6"

lib/Zonemaster/CLI.pm
PR #307 updates how the table layout is computed. It appears that the severity strings are translated and this can break the layout. This PR fixes that by computing the width taking into account the length of the translated severity strings.
Follow-up #307.
Fixes #334
* update severity column width computation
Check that when changing the level and the locale, the table layout does not break.
```
zonemaster-cli --locale es_ES.utf8 --level CRITICAL zonemaster.net
zonemaster-cli --locale es_ES.utf8 --level DEBUG zonemaster.net
zonemaster-cli --locale sv_SE.utf8 --level CRITICAL zonemaster.net
```
=> Fix table layout

lib/Zonemaster/CLI.pm, script/zonemaster-cli
This PR fixes 2 small error/bugs discovered during v2023.1 release testing.
#308 https://github.com/zonemaster/zonemaster-cli/pull/309
v2023.1 release testing comment https://github.com/zonemaster/zonemaster-cli/pull/308#issuecomment-1570279972
v2023.1 release testing comment https://github.com/zonemaster/zonemaster-cli/pull/309#issuecomment-1570297400
* fix ineffective `--no-json-translate` option
* show deprectation warning with option alias `--[no-]json_translate`
* Check that `--[no-]json_translate` option gives a deprecation warning. 
* Check that `--no-json-translate` does not output the `message` key.
=> Fix option --[no-]json-translate

Changes, Makefile.PL, lib/Zonemaster/CLI.pm
Updates files `Changes`, `Makefile.PL` and `CLI.pm`.
=> Preparation for release v2023.1 (CLI)

lib/Zonemaster/CLI.pm, script/zonemaster-cli
Seen as a bug, see comment https://github.com/zonemaster/zonemaster-cli/pull/333#discussion_r1247918347
All should work:
```
zonemaster-cli --show-testcase --test basic/basic01 kyoto
zonemaster-cli --show-testcase --test BASIC/BASIC01 melbourne
zonemaster-cli --show-testcase --test BAsiC rio
zonemaster-cli --show-testcase --test bAsIc/BaSiC01 quebec
```
=> Make --test case-insensitive

lib/Zonemaster/CLI.pm
Fix raw output
When using https://github.com/zonemaster/zonemaster-engine/pull/1302 the raw ouput is broken as the CLI was relying on the fact that module / testcase / tag to strip them from the message.
Instead of changing the regex, let's use a new method that return only the message arguments, which is less error prone.
* Use the new method `$entry->argstr` instead of removing the prefix of the output of `$entry->string`.
Check that the raw ouput working correctly, in particular check that after the message tag only the arguments are displayed and no garbage of any sort.
Before the PR
```
% zonemaster-cli --level info --show-module --show-testcase afnic.fr --test connectivity --raw
0.00 INFO     System       Unspecified    GLOBAL_VERSION  ystem:Unspecified:GLOBAL_VERSION version=v4.7.3 …
```
=> Fix raw ouput

lib/Zonemaster/CLI.pm, script/zonemaster-cli
Make it possible to only pass the name of a testcase to the `--test` option.
The following commands are now both ok and identical:
```
zonemaster-cli --test basic/basic01
zonemaster-cli --test basic01
```
Fixes #232
* allow passing only a testcase name to the `--test` option
* run all testcases from the Basic module:
```
zonemaster-cli --test basic
```
* run only one testcase
```
zonemaster-cli --test basic/basic01
zonemaster-cli --test basic01
```
=> Extend --test option to allow passing only a testcase

Dockerfile, Makefile.PL, lib/Zonemaster/CLI.pm
This PR fixes a couple of issues related to command line argument handling.
This PR fixes items 1 and 2 in #364.
* Domain names "" and "0" are not rejected as missing domain names.
* The diagnostics/results separator is printed after input validation is completed.
* As a drive-by change, the unused Test::Reflow dependency is also removed.
Zonemaster CLI should present the following behaviors:
```
$ zonemaster-cli --show-testcase --no-ipv6 --test basic/basic01 
Must give the name of a domain to test.
$ zonemaster-cli --show-testcase --no-ipv6 --test basic/basic01 ''
Domain name is empty
$ zonemaster-cli --show-testcase --no-ipv6 --test basic/basic01 0 …
```
=> Fix domain name command line argument handling

Makefile.PL, lib/Zonemaster/CLI.pm, script/zonemaster-cli, t/usage.t
This PR concerns itself with validation and dispatching of user-provided command line options to zonemaster-cli.
Limitations:
* The actual implementations of the options are only within scope here to the extent that proper dispatching can be determined. Any other problems with option implementations are deferred to separate issues.
* Details in how command line arguments are parsed are out of scope.
* The --progress option is out of scope.
This PR aims to establish a sufficient regression testing suite for the stated scope. It would be great if we didn't need to perform any manual testing for this particular aspect of the application when switching out the command line parsing library.
As part of #68 we plan to drop our dependency on Moose and MooseX::Getopt::GLD. That will affect every …
=> Improved test coverage

MANIFEST.SKIP, t/manifest.t
Run 'make distcheck' in tests.
I followed what was done in "https://github.com/zonemaster/zonemaster-engine/pull/903"
It's the same as "https://github.com/zonemaster/zonemaster-ldns/pull/195"
Fixes #199 
Make sure we don't interfere with the release process:
```
git clean -dfx   # Start out with a clean repository
perl Makefile.PL # Generate the top-level Makefile
make all         # Generate MO files and modules.txt
make distcheck   # Verify that distcheck doesn't report any missing or unrecognized files
```
Run the unit tests in the source directory:
```
make distcheck     # Make sure distcheck doesn't report any missing or unrecognized files
prove t/manifest.t # Verify the new test passes
touch new.file  # Create a file but don't add it to MANIFEST
prove t/manifest.t # Verify the new …
```
=> Check MANIFEST when PR is created

lib/Zonemaster/CLI.pm
This separate CLI errors from Engine errors.
Errors on CLI argument are catch before displaying the header.
Fixes #358 
I have split CLI argument verification from Engine settings.
I have also add regex validation for '--ds' arguments
Stress test zonemaster-cli with various '--ns' and '--ds' arguments.
Errors from command line input validation must be display **before** any header.
Errors from the Engine must be formatted correctly **after** the header.
here some example to cmd to run:
```
zonemaster-cli --show-testcase --no-ipv6 --test basic/basic01 zonemaster.net --ns 'ns1.zonemaster.net'
zonemaster-cli --show-testcase  example.fr --ns 'ns1.zonemaster..fr.'
zonemaster-cli --show-testcase  example.fr --ns 'ns1.zonemaster.fr/542.0.0.1'
zonemaster-cli --show-testcase  example.fr --ns …
```
=> Fixing errors display when using options '--ns' or '--ds'

t/usage.t
This PR disables a couple of unit tests that hang on FreeBSD.
The problem was reported in #388.
Until #388 is fixed we can't rely on the automatic tests for the `--dump-profile` option.
Two tests in t/usage.t are skipped (on all OSes)
The `t/usage.t` test should terminate successfully on FreeBSD.
=> Disable failing tests for now

.travis.yml, Dockerfile, MANIFEST, Makefile.PL, lib/Zonemaster/CLI.pm, script/zonemaster-cli, t/pod.t, t/usage.t, t/usage.wrapper.pl
This PR kills two birds with one stone:
* It fixes the discrepancy between perldoc zonemaster-cli and zonemaster-cli --help, and
* it migrates away from Moose and Moosex::Getopt::GLD.
* Fixes #68.
* I've tried to keep this PR conservative with regards to improving the actual help text. I have a lot of improvements in mind but I'm deferring them to one or more followup PRs. See #389.
Application:
* Instead of using Moose and Moosex::Getopt::GLD we now Getopt::Long and Pod::Usage which are both Perl core modules.
* I merged the best parts of the --help and perldoc usage texts. As I worked through them I realized there was a lot of room for further improvement. I tried to be conservative making improvements but in some cases I couldn't help myself.
Tests:
* A unit test is added to make sure …
=> Make usage documentation consistent and also demoose

README.md, lib/Zonemaster/CLI.pm, script/zonemaster-cli
Make the --help text more focused and organized.
* Because much of the documentation for CLI lives in the zonemaster/zonemaster repository, there's a dual PR in that repository. zonemaster/zonemaster#1309.
* This is a followup to #371 and includes those commits. It also includes the commits of #395 which fixes a bug introduced in the former.
* I've tried to keep this PR focused on structure and make as few changes as possible to the actual language. I have a lot of improvements in mind for that as well, but I'm saving those for one or more followup PRs for the next release.
* Group options for easier navigation.
* Limit the contents and clutter of the --help output, but make sure to point to the man page.
* Include list of severity levels in --help output again (after removal in #371).
* …
=> Organize --help text

.travis.yml, lib/Zonemaster/CLI.pm, t/usage.t
* Commit b6f34dd: Some of the gettext printed messages in CLI was not correctly configured. You cannot have an Perl variable in the message. That has been corrected by this PR. Without the change PO handling will not work.
* Commit b65d5f54: Dependency for Engine added by zonemaster/zonemaster/pull/1307 and zonemaster/zonemaster/pull/1314, respectively, must be included for CI, or else Travis will fail. This PR fixes that.
* Review
* Unit test should work
* Run `zonemaster-cli` with input data that should be captured, e.g. non-existing profile file.
=> Corrects gettext code and adds dependency required by CI (Travis)

.travis.yml
This PR just removes deprecated comment not relevant anymore. Does not affect anything.
Moose is not used in CLI anymore.
Review.
=> Cleanup of .travis.yml

Dockerfile
This PR fixes a warning that appeared when running `docker build` on my test system (Rocky Linux 9):
```
1 warning found (use docker --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
```
Release testing for 2024.2.
- Write “FROM … AS” instead of “FROM … as” in the Dockerfile.
Build the container for `zonemaster-cli` according to the [documented procedure](https://github.com/zonemaster/zonemaster/blob/develop/docs/internal/maintenance/ReleaseProcess-create-docker-image.md). No warning should appear. (Although one should also check if the warning is generated by reverting this change.)
=> Write “AS” in uppercase in Dockerfile

script/zonemaster-cli
This PR replaces the text in the “See also” section of the man page/POD documentation in the `zonemaster-cli` command line utility with some information that I deemed more useful.
The previous text had a link to a Perl package called Zonemaster. But no such package actually exists, so the link is broken. Also, it looks very awkward when reading the man page version of this documentation, because links like these cannot be clicked on and just appear as “Zonemaster”. So the whole section reads as “See also: Zonemaster” in the man page.
Release testing for 2024.2; PR #389.
* Rewrite “See also” section;
* As a drive-by change, some minor edits (e.g. replacing contractions such as “they’re” with their fully expanded equivalents such as “they are”) and removal of one typo.
Run `perldoc -o man …
=> Provide more useful link in man page

lib/Zonemaster/CLI.pm
This PR fixes a problem where, in one particular set of circumstances (caused by user error), `zonemaster-cli` fails to display messages on the terminal.
Adding fake delegation by means of the --ns command-line option can sometimes elicit early Zonemaster::Engine log messages that are lost because the translator isn’t properly initialized at this stage. For reasons that I do not understand fully yet, this situation causes a condition where the zonemaster-cli script displays no message at all, even though it should.
As a workaround for this problem, we set the callback to Zonemaster::Engine::Logger twice. First, we set it to a closure that simply appends them to a queue of yet-to-be-printed messages. Right after the translator is initialized, we print the header and messages stored by the …
=> Zonemaster::CLI: don’t lose early log messages

MANIFEST, share/sl.po
Merge master into develop (CLI)
Adding slovenian translation (sl.po)
...
=> Adds translation to Slovenian
